# utils/report.py
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.units import cm
from datetime import datetime

def generate_pdf(summary: dict, save_path: str):
    """
    summary keys expected:
      title, total_invoices, anomalies, anomaly_rate, high_risk_suppliers, ts
    """
    c = canvas.Canvas(save_path, pagesize=A4)
    w, h = A4

    # Header band
    c.setFillColorRGB(0.07, 0.07, 0.12)
    c.rect(0, h-3*cm, w, 3*cm, stroke=0, fill=1)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 18)
    c.drawString(2*cm, h-2*cm, summary.get("title", "Counterfeit Detection Report"))
    c.setFont("Helvetica", 10)
    c.drawString(2*cm, h-2.6*cm, f"Generated: {summary.get('ts', datetime.utcnow().isoformat())} UTC")

    # KPIs
    y = h - 4.2*cm
    c.setFont("Helvetica-Bold", 14)
    c.setFillColor(colors.HexColor("#7C4DFF"))
    c.drawString(2*cm, y, "Key Metrics")

    c.setFillColor(colors.white)
    c.setFont("Helvetica", 11)
    y -= 1.0*cm
    c.drawString(2*cm, y, f"Total invoices: {summary.get('total_invoices', 0)}")
    y -= 0.7*cm
    c.drawString(2*cm, y, f"Anomalies: {summary.get('anomalies', 0)}")
    y -= 0.7*cm
    c.drawString(2*cm, y, f"Anomaly rate: {summary.get('anomaly_rate','0%')}")
    y -= 0.7*cm
    c.drawString(2*cm, y, f"High-risk suppliers (score ≥ 70): {summary.get('high_risk_suppliers', 0)}")

    # Footer
    c.setFillColor(colors.grey)
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(2*cm, 1.5*cm, "Generated by AI-Powered Supply Chain Transparency (demo)")

    c.showPage()
    c.save()
